CREATE TABLE XCUSTOMTABLE(
	GENERATED_ID  INTEGER NOT NULL,
	MY_ID SMALLINT,
	TEXT_COL VARCHAR(50),
	INT_COL SMALLINT,
	PRIMARY KEY(GENERATED_ID)
);

SELECT * FROM XCUSTOMTABLE;
SELECT * FROM KEYS WHERE TABLENAME LIKE 'X%';

INSERT INTO KEYS(KEYS_ID, TABLENAME, COLUMNNAME, COUNTER, PREFETCHSIZE, LOWERBOUND, UPPERBOUND,OPTCOUNTER)
VALUES ((SELECT MAX(KEYS_ID) + 1 FROM KEYS), 'XCUSTOMTABLE','GENERATED_ID',1,1,0,2147483647,1);
commit;
--dataload.bat C:\Users\Admin\Downloads\custom-dataload\wc-dataload.xml -DConsoleHandler.level=FINE
--C:\Users\Admin\Downloads\custom-dataload\wc-dataload.xml
UPDATE KEYS SET PREFETCHSIZE = 20 WHERE KEYS_ID= -1;